# Generated by Django 5.2.5 on 2025-08-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-create_at", "-update_at"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="create_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="updated_at",
            new_name="update_at",
        ),
    ]
