# Generated by Django 5.2.5 on 2025-08-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-update_at"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="create_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated_at",
            new_name="update_at",
        ),
    ]
